version: '3.1'
services:
  django-tutorial:
    container_name: django_jenkins
    image: legnakra/django_jenkins
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      HOST: db_mariadb
      USUARIO: django
      CONTRA: django
      BASE_DATOS: django
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.org
    ports:
      - 8100:8888
    depends_on:
      - db_django
  db:
    container_name: db_mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: django
    volumes:
      - mariadb_data_django_jenkins:/var/lib/mysql
volumes:
    mariadb_data_django_jenkins:
