version: '3.8'
services:
  django_tutorial_jenkins:
    container_name: django_tutorial_jenkins
    image: legnakra/django_jenkins
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      HOST: mariadb_django_jenkins
      USUARIO: django
      CONTRA: django
      BASE_DATOS: django
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.org
    ports:
      - 8100:8888
    depends_on:
      - mariadb_django_jenkins
  mariadb_django_jenkins:
    container_name: mariadb_django_jenkins
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: django
    volumes:
      - mariadb_data_django_jenkins:/var/lib/mysql
volumes:
    mariadb_data_django_jenkins:
